/**
 * 취약점 지식 시드 — 앱 최초 실행 시 그래프 DB에 적재되는 기본 노드 집합.
 * AST 패턴형(소스코드 대조용)과 패키지 CVE형(의존성 대조용)으로 구성.
 */
import type { VulnerabilityNode } from './types';

const now = (): string => new Date().toISOString();

export const SEED_VULNERABILITIES: VulnerabilityNode[] = [
  {
    kind: 'vulnerability',
    id: 'VULN-001',
    title: 'Dangerous Eval',
    description: '임의의 코드를 실행하는 eval() 함수가 사용되었습니다. 보안상 매우 위험합니다.',
    severity: 'high',
    astSignature: { calleeName: 'eval' },
    references: ['https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/eval'],
    updatedAt: now(),
  },
  {
    kind: 'vulnerability',
    id: 'VULN-002',
    title: 'Hardcoded Secret',
    description: '민감한 값(password/secret/key)이 소스코드에 하드코딩되어 있습니다.',
    severity: 'high',
    astSignature: { identifierNames: ['password', 'secret', 'privatekey', 'api_key', 'apikey', 'token'] },
    references: ['https://cwe.mitre.org/data/definitions/798.html'],
    updatedAt: now(),
  },
  {
    kind: 'vulnerability',
    id: 'VULN-003',
    title: 'DOM XSS via innerHTML',
    description: 'innerHTML 대입은 XSS 공격 경로가 됩니다. textContent 또는 DOMPurify 같은 새니타이저를 사용하세요.',
    severity: 'high',
    astSignature: { memberName: 'innerHTML' },
    references: ['https://cwe.mitre.org/data/definitions/79.html'],
    updatedAt: now(),
  },
  {
    kind: 'vulnerability',
    id: 'VULN-004',
    title: 'Command Injection via child_process',
    description: 'child_process.exec/execSync에 외부 입력이 전달되면 명령어 주입이 가능합니다. execFile/spawn argv 방식을 사용하세요.',
    severity: 'critical',
    astSignature: { memberName: 'exec', calleeName: 'exec' },
    references: ['https://cwe.mitre.org/data/definitions/78.html'],
    updatedAt: now(),
  },
  {
    kind: 'vulnerability',
    id: 'VULN-005',
    title: 'Dangerous Function Constructor',
    description: "Function() 생성자는 eval과 동등한 코드 실행 수단입니다. 사용자 입력과 함께 사용하지 마세요.",
    severity: 'high',
    astSignature: { calleeName: 'Function' },
    references: ['https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Function'],
    updatedAt: now(),
  },
  {
    kind: 'vulnerability',
    id: 'VULN-006',
    cveId: 'CVE-2020-28500',
    title: 'lodash Prototype Pollution',
    description: 'lodash 4.17.20 이하에서 프로토타입 오염 취약점이 보고되었습니다. 4.17.21 이상으로 업데이트하세요.',
    severity: 'high',
    affectedPackage: 'lodash',
    versionRange: '<4.17.21',
    references: ['https://nvd.nist.gov/vuln/detail/CVE-2020-28500'],
    updatedAt: now(),
  },
  {
    kind: 'vulnerability',
    id: 'VULN-007',
    cveId: 'CVE-2021-3749',
    title: 'axios Credential Leak',
    description: 'axios 0.21.1 이하에서 특정 조건에 자격 증명이 노출될 수 있습니다. 0.21.2 이상으로 업데이트하세요.',
    severity: 'medium',
    affectedPackage: 'axios',
    versionRange: '<0.21.2',
    references: ['https://nvd.nist.gov/vuln/detail/CVE-2021-3749'],
    updatedAt: now(),
  },
  {
    kind: 'vulnerability',
    id: 'VULN-008',
    cveId: 'CVE-2021-44906',
    title: 'minimist Prototype Pollution',
    description: 'minimist 1.2.7 이하에서 프로토타입 오염 취약점이 보고되었습니다. 1.2.8 이상으로 업데이트하세요.',
    severity: 'high',
    affectedPackage: 'minimist',
    versionRange: '<1.2.8',
    references: ['https://nvd.nist.gov/vuln/detail/CVE-2021-44906'],
    updatedAt: now(),
  },
  {
    kind: 'vulnerability',
    id: 'VULN-009',
    cveId: 'CVE-2020-7660',
    title: 'serialize-javascript XSS',
    description: 'serialize-javascript 3.1.0 이하에서 XSS 취약점이 보고되었습니다. 3.1.1 이상으로 업데이트하세요.',
    severity: 'medium',
    affectedPackage: 'serialize-javascript',
    versionRange: '<3.1.1',
    references: ['https://nvd.nist.gov/vuln/detail/CVE-2020-7660'],
    updatedAt: now(),
  },
];
